#!/bin/bash
for file in /home/eren/Downloads/*.flac; do
    opusenc --bitrate 256 "$file" "${file%.flac}.opus"
done

for file in /home/eren/Downloads/*.flac; do
    rm "$file"
done

for file in /home/eren/Downloads/*.opus; do
    mv "$file" "/home/eren/Music"
done
