#!/bin/bash

_user="$(id -u -n)"

# Converts FLAC to 256-bit OPUS
for file in /home/"$_user"/Downloads/*.flac; do
    [ -f "$file" ] && opusenc --bitrate 256 "$file" "${file%.flac}.opus" && rm "$file"
done

# Moves the newly created OPUS files
for file in /home/"$_user"/Downloads/*.opus; do
    [ -f "$file" ] && mv "$file" "/home/$_user/Music"
done
